MvcMusicStore/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Models;
using MvcMusicStore.Services.Checkout;
using MvcMusicStore.ViewModels.CheckoutViewModels;

namespace MvcMusicStore.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        private CheckoutService _service;

        public CheckoutController(CheckoutService service)
        {
            this._service = service;
        }

        private const string PromoCode = "FREE";


        [HttpGet]
        public ActionResult AdressAndPayment()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult AdressAndPayment(CheckoutAdressAndPaymentViewModel dataForOrder)
        {
            var cartContent = this._service.CheckContent(this.HttpContext.User.Identity.Name);
            if (cartContent == 0)
            {
                return RedirectToAction("AdressAndPayment");
            }

            try
            {
                if (string.Equals(dataForOrder.PromoCode, PromoCode, StringComparison.OrdinalIgnoreCase) == false)
                {
                    return View(dataForOrder);
                }

                else
                {
                    var idForCompleting = this._service.MakeOrder(dataForOrder, this.HttpContext.User.Identity.Name);
                    return RedirectToAction("Complete", new { id = idForCompleting });
                }
            }
            catch
            {
                // Invalid - display with errors
                return View(dataForOrder);
            }
        }

       
        public ActionResult Complete(string id)
        {
            // Vaidate customer owns this order
            try
            {
                var order = this._service.CheckOrder(id);
                var numberOfOrder = order.GetHashCode();
                return View(numberOfOrder);
            }

            catch
            {
                return View("Error");
            }
        }
    }
}

MvcMusicStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MvcMusicStore.Documents;
using MvcMusicStore.Models;
using MvcMusicStore.Services.ShoppingCart;
using MvcMusicStore.ViewModels;
using MvcMusicStore.ViewModels.ShoppingCartViewModels;

namespace MvcMusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private ShoppingCartService _service;

        public ShoppingCartController(ShoppingCartService service)
        {
            this._service = service;
        }


        public ActionResult Index()
        {
            var indexViewModel = this._service.GetIndexViewModel(HttpContext.User.Identity.Name);
            return View(indexViewModel);
        }

        [Authorize]
        public ActionResult AddToCart(string id)
        {
            this._service.AddToCart(id, this.HttpContext.User.Identity.Name);
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/"554776586754h5k455ggtge"
        [HttpPost]
        public ActionResult RemoveFromCart(string id)
        {
            var results = this._service.RemoveFromCart(id, this.HttpContext.User.Identity.Name);
            return Json(results);
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            if (String.IsNullOrEmpty(this.HttpContext.User.Identity.Name))
            {
                var summaryViewModel = this._service.GetEmptyCart();
                return PartialView(summaryViewModel);
            }

            else
            {
                var summaryViewModel = this._service.GetCartSummaryViewModel(this.HttpContext.User.Identity.Name);
                return PartialView(summaryViewModel);
            }
        }
    }
}

MvcMusicStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Models;
using MvcMusicStore.Services.Store;
using MvcMusicStore.ViewModels.StoreViewModels;

namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
        private StoreService _service;

        public StoreController(StoreService service)
        {
            this._service = service;
        }


        public ActionResult Index()
        {
            var indexViewModel = this._service.GetIndexViewModel();
            return View(indexViewModel);
        }


        public ActionResult Browse(string genre)
        {
            var browseViewModel = this._service.GetBrowseViewModel(genre);
            return View(browseViewModel);
        }


        public ActionResult Details(string id)
        {
            var detailsViewModel = this._service.GetDetailsViewModel(id);
            return View(detailsViewModel);
        }


        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genresViewModel = this._service.GetGenreMenuViewModel();
            return PartialView(genresViewModel);
        }
    }
}

MvcMusicStore/Views/ShoppingCart/CartSummary.cshtml
@model MvcMusicStore.ViewModels.ShoppingCartViewModels.ShoppingCartSummaryViewModel
@Html.ActionLink("Cart (" + Model.CartCount + ")", "Index", "ShoppingCart",  new {id = "cart-status"})

MvcMusicStore/Views/ShoppingCart/Index.cshtml
@model MvcMusicStore.ViewModels.ShoppingCartViewModels.ShoppingCartIndexViewModel
@{
    ViewBag.Title = "Shopping cart";
}

<script src="/Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != "") {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $("#row-" + data.DeleteId).fadeOut("slow");
                        } else {
                            $("#item-count-" + data.DeleteId).text(data.ItemCount);
                        }
                        $("#cart-total").text(data.CartTotal);
                        $("#update-message").text(data.Message);
                        $("#cart-status").text("Cart (" + data.AmountOfPurchase + ")");
                    });
            }
        });
    });
</script>

<h3><em>Review</em> your cart:</h3>

<p class="button">
    @Html.ActionLink("Checkout >>", "AdressAndPayment", "Checkout")
</p>
<div id="update-message">
</div>
<table>
    <tr>
        <th>Album Name</th>
        <th>Price (each)</th>
        <th>Quantity</th>
        <th></th>
    </tr>

    @foreach (var item in Model.Albums)
    {
        if (!Model.VariousTitles.Contains(item.Title))
        {
            Model.VariousTitles.Add(item.Title);
            <tr id="row-@item.AlbumId">
                <td>@Html.ActionLink(item.Title, "Details", "Store", new { id = item.AlbumId }, null)</td>
                <td>@item.Price</td>
                <td id="item-count-@item.AlbumId">@Model.Albums.Count(x => x.Title == item.Title)</td>
                <td><a href="#" class="RemoveLink" data-id="@item.AlbumId">Remove from cart</a></td>
            </tr>
        }
        
    }
    <tr>
        <td>Total</td>
        <td></td>
        <td></td>
        <td id="cart-total">@Model.TotalPrice</td>
    </tr>
</table>